name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Create virtual environment
        env:
          BIN: ${{ matrix.os == 'ubuntu-latest' && 'Scripts' || 'bin' }}
        run: |
          python -m venv .venv
          echo "$GITHUB_WORKSPACE/.venv/$BIN" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Build Rust extension
        run: maturin develop --release

      - name: Deploy docs to GitHub Pages
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --force
        # TODO: eventually switch to --strict
        # run: mkdocs gh-deploy --strict --force

      - name: Test that docs build without error
        if: github.event_name == 'pull_request'
        run: mkdocs build
        # run: mkdocs build --strict
